export const content = {
  en: {
    skip: 'Skip intro',
    introLine: 'Connecting a smarter tomorrow.',
    nav: [
      ['home', 'Home'],
      ['solutions', 'Solutions'],
      ['products', 'Products'],
      ['why', 'Why BAMA'],
      ['ecosystem', 'Smart ecosystem'],
      ['about', 'About'],
      ['contact', 'Contact'],
    ],
    explore: 'Explore solutions',
    hero: {
      title: ['Smarter connections.', 'Smarter access.', 'One ecosystem.'],
      body: 'BAMA Smart Solution brings networking, access, security, home intelligence, sensors and connected devices into one expandable ecosystem.',
      secondary: 'View products',
      signal: 'One connected smart ecosystem',
    },
    solutions: {
      title: 'Smart solutions for connected spaces',
      intro: 'From the network to the entrance, each layer is selected to work as part of a clear, expandable environment.',
      current: 'Available now',
      future: 'Ecosystem direction',
      items: [
        {
          number: '01',
          title: 'Advanced networking',
          body: 'Wi-Fi 7, high-speed connectivity, multi-device capacity and fast roaming for homes and offices.',
          points: ['Wi-Fi 7', 'High-speed connectivity', 'Home and office networks'],
        },
        {
          number: '02',
          title: 'Smart access',
          body: 'Keyless entrances with facial recognition, fingerprint and password access for modern spaces.',
          points: ['3D face recognition', 'Fingerprint access', 'Keyless environments'],
        },
        {
          number: '03',
          title: 'Smart security',
          body: 'A future ecosystem layer for connected cameras, monitoring and coordinated protection.',
          points: ['Connected monitoring', 'Future camera integration', 'Coordinated protection'],
        },
        {
          number: '04',
          title: 'Smart living',
          body: 'A future foundation for sensors, automation, lighting and intelligent devices across the space.',
          points: ['Home automation', 'Sensors and lighting', 'Connected devices'],
        },
      ],
    },
    featured: {
      title: 'Featured smart products',
      intro: 'Two confirmed products. One much wider smart-technology direction.',
      discover: 'Discover product',
      category: 'Category',
      allProducts: 'Explore All Smart Products',
      ecosystemLabel: 'The wider BAMA ecosystem',
    },
    ecosystem: {
      title: 'One smart ecosystem',
      body: 'A connected space works best when its network, entrances, security and devices share one considered foundation.',
      labels: ['Internet', 'Networking', 'Access', 'Security', 'Living', 'Devices'],
      hint: 'Move across the connected points',
    },
    why: {
      title: 'Built for the space you have, ready for what comes next.',
      items: [
        ['Selected technology', 'Products are chosen for practical performance and a clear role in the wider environment.'],
        ['Seamless integration', 'Networking and access are planned as connected layers, not isolated devices.'],
        ['Professional installation', 'The experience is structured around correct placement, setup and project needs.'],
        ['Built to expand', 'The foundation can grow into security, automation, sensors and future connected devices.'],
      ],
    },
    useCases: {
      title: 'Built around your space.',
      body: 'The same connected foundation adapts to different priorities, from coverage at home to managed access at work.',
      items: [
        ['Homes', 'Reliable coverage and considered access for everyday connected living.'],
        ['Offices', 'Networks and entrances planned for teams, devices and movement.'],
        ['Retail', 'Stable connectivity and controlled access around active commercial spaces.'],
        ['Hospitality', 'Connected guest environments with discreet, dependable infrastructure.'],
      ],
    },
    about: {
      title: 'Technology that belongs in the space.',
      body1: 'BAMA Smart Solution is building a broad smart-technology ecosystem for modern homes and businesses.',
      body2: 'We connect networking, access, security, home intelligence, sensors and future devices through one clear, expandable experience.',
    },
    future: {
      title: ['Today, connectivity and access.', 'Tomorrow, the whole smart space.'],
      body: 'The BAMA ecosystem is designed to expand carefully as new categories become available.',
      label: 'Future ecosystem capabilities',
      items: ['Smart security', 'Automation', 'Sensors', 'Lighting', 'Connected devices'],
    },
    contact: {
      title: "Let's make your space smarter.",
      body: 'Choose the conversation that best fits your space or project.',
      options: ['Product inquiry', 'Installation', 'Business and project solutions', 'General inquiry'],
      detailsPending: 'Direct WhatsApp, phone and email details are ready to be connected as soon as the official company information is supplied.',
      selected: 'Selected inquiry',
    },
    footer: {
      statement: 'Connecting a smarter tomorrow.',
      country: 'Saudi Arabia',
      copyright: '© 2026 BAMA Smart Solution.',
    },
    productsPage: {
      title: 'Smart Products',
      body: 'Six connected product worlds establish the full BAMA direction. Wi-Fi 7 and Smart Access are confirmed now; the remaining categories show how the ecosystem is designed to grow.',
      current: 'Available now',
      future: 'Coming to the ecosystem',
      viewCategory: 'Explore category',
      confirmedProduct: 'Confirmed product',
      categoryDirection: 'Category direction',
      allProducts: 'All Smart Products',
    },
    categoryPage: {
      back: 'All Smart Products',
      available: 'Available now',
      future: 'Coming to the ecosystem',
      confirmed: 'Confirmed product',
      direction: 'Future category direction',
      examples: 'Planned category scope',
      viewProduct: 'View product',
    },
    detail: {
      overview: 'Overview',
      specifications: 'Key specifications',
      environments: 'Ideal environments',
      benefits: 'Connected benefits',
      inquiry: 'Request product inquiry',
      installation: 'Discuss installation',
      related: 'Related solution',
      back: 'All products',
    },
    notFound: {
      title: 'This page is not connected.',
      body: 'The address may have changed or the page is not available.',
      action: 'Return home',
    },
  },
  ar: {
    skip: 'تخطي المقدمة',
    introLine: 'نربط اليوم بمستقبل أكثر ذكاءً.',
    nav: [
      ['home', 'الرئيسية'],
      ['solutions', 'الحلول'],
      ['products', 'المنتجات'],
      ['why', 'لماذا BAMA'],
      ['ecosystem', 'المنظومة الذكية'],
      ['about', 'عن BAMA'],
      ['contact', 'تواصل معنا'],
    ],
    explore: 'استكشف الحلول',
    hero: {
      title: ['اتصال أذكى.', 'دخول أذكى.', 'منظومة واحدة.'],
      body: 'تجمع BAMA Smart Solution الشبكات والدخول والأمان والمنزل الذكي والحساسات والأجهزة المتصلة ضمن منظومة واحدة قابلة للتوسع.',
      secondary: 'عرض المنتجات',
      signal: 'منظومة ذكية متصلة واحدة',
    },
    solutions: {
      title: 'حلول ذكية لمساحات أكثر اتصالاً',
      intro: 'من الشبكة إلى المدخل، نختار كل طبقة لتعمل ضمن بيئة واضحة وقابلة للتوسع.',
      current: 'متوفر حالياً',
      future: 'توجه مستقبلي للمنظومة',
      items: [
        {
          number: '٠١',
          title: 'الشبكات المتقدمة',
          body: 'واي فاي 7 واتصال عالي السرعة وسعة لأجهزة متعددة وتنقل سريع للمنازل والمكاتب.',
          points: ['واي فاي 7', 'اتصال عالي السرعة', 'شبكات المنازل والمكاتب'],
        },
        {
          number: '٠٢',
          title: 'الدخول الذكي',
          body: 'مداخل بدون مفاتيح مع التعرّف على الوجه وبصمة الإصبع والرمز السري للمساحات الحديثة.',
          points: ['تعرّف ثلاثي الأبعاد على الوجه', 'بصمة الإصبع', 'دخول بدون مفتاح'],
        },
        {
          number: '٠٣',
          title: 'الأمان الذكي',
          body: 'طبقة مستقبلية ضمن المنظومة للكاميرات المتصلة والمراقبة والحماية المنسقة.',
          points: ['مراقبة متصلة', 'تكامل مستقبلي للكاميرات', 'حماية منسقة'],
        },
        {
          number: '٠٤',
          title: 'الحياة الذكية',
          body: 'أساس مستقبلي للمستشعرات والأتمتة والإضاءة والأجهزة الذكية في مختلف أنحاء المساحة.',
          points: ['أتمتة المنزل', 'المستشعرات والإضاءة', 'الأجهزة المتصلة'],
        },
      ],
    },
    featured: {
      title: 'المنتجات الذكية المختارة',
      intro: 'منتجان مؤكدان اليوم، وتوجه أوسع بكثير للتقنيات الذكية.',
      discover: 'اكتشف المنتج',
      category: 'الفئة',
      allProducts: 'استكشف جميع المنتجات الذكية',
      ecosystemLabel: 'منظومة BAMA الأوسع',
    },
    ecosystem: {
      title: 'منظومة ذكية واحدة',
      body: 'تعمل المساحة المتصلة بكفاءة أكبر عندما تشترك الشبكة والمداخل والأمان والأجهزة في أساس واحد مدروس.',
      labels: ['الإنترنت', 'الشبكات', 'الدخول', 'الأمان', 'الحياة الذكية', 'الأجهزة'],
      hint: 'تنقّل بين نقاط الاتصال',
    },
    why: {
      title: 'مصمم لمساحتك اليوم، وجاهز لما بعدها.',
      items: [
        ['تقنيات مختارة بعناية', 'نختار المنتجات لأدائها العملي ولدورها الواضح ضمن البيئة المتكاملة.'],
        ['تكامل سلس', 'نخطط للشبكات والدخول كطبقات متصلة، لا كأجهزة منفصلة.'],
        ['تركيب احترافي', 'نبني التجربة حول التوزيع الصحيح والإعداد واحتياجات المشروع.'],
        ['جاهز للتوسع', 'يمكن للأساس أن يتطور ليشمل الأمان والأتمتة والمستشعرات والأجهزة المتصلة مستقبلاً.'],
      ],
    },
    useCases: {
      title: 'حلول مصممة لمساحتك.',
      body: 'يتكيف الأساس المتصل مع أولويات مختلفة، من تغطية المنزل إلى إدارة الدخول في بيئات العمل.',
      items: [
        ['المنازل', 'تغطية موثوقة ودخول مدروس لحياة يومية أكثر اتصالاً.'],
        ['المكاتب', 'شبكات ومداخل مخططة للفرق والأجهزة والحركة.'],
        ['المتاجر', 'اتصال مستقر ودخول منظم للمساحات التجارية النشطة.'],
        ['الضيافة', 'بيئات ضيافة متصلة ببنية تقنية هادئة وموثوقة.'],
      ],
    },
    about: {
      title: 'تقنية تنتمي إلى المساحة.',
      body1: 'تبني BAMA Smart Solution منظومة واسعة للتقنيات الذكية للمنازل والأعمال الحديثة.',
      body2: 'نجمع الشبكات والدخول والأمان والمنزل الذكي والحساسات والأجهزة المستقبلية ضمن تجربة واحدة واضحة وقابلة للتوسع.',
    },
    future: {
      title: ['اليوم اتصال ودخول ذكي.', 'غداً منظومة متكاملة للمساحة الذكية.'],
      body: 'صُممت منظومة BAMA لتتوسع بعناية مع توفر فئات تقنية جديدة.',
      label: 'قدرات مستقبلية للمنظومة',
      items: ['الأمان الذكي', 'الأتمتة', 'المستشعرات', 'الإضاءة', 'الأجهزة المتصلة'],
    },
    contact: {
      title: 'خلّ مساحتك أذكى.',
      body: 'اختر نوع التواصل الأنسب لمساحتك أو مشروعك.',
      options: ['استفسار عن منتج', 'طلب تركيب', 'حلول الشركات والمشاريع', 'استفسار عام'],
      detailsPending: 'قنوات واتساب والهاتف والبريد الإلكتروني جاهزة للربط فور تزويدنا ببيانات التواصل الرسمية للشركة.',
      selected: 'نوع الاستفسار المختار',
    },
    footer: {
      statement: 'نربط اليوم بمستقبل أكثر ذكاءً.',
      country: 'المملكة العربية السعودية',
      copyright: '© 2026 BAMA Smart Solution.',
    },
    productsPage: {
      title: 'المنتجات الذكية',
      body: 'ستة عوالم مترابطة توضح التوجه الكامل لـ BAMA. يتوفر Wi-Fi 7 والدخول الذكي كمنتجات مؤكدة، بينما توضح الفئات الأخرى مسار توسع المنظومة.',
      current: 'متوفر حالياً',
      future: 'قريباً ضمن المنظومة',
      viewCategory: 'استكشف الفئة',
      confirmedProduct: 'منتج مؤكد',
      categoryDirection: 'توجه الفئة',
      allProducts: 'جميع المنتجات الذكية',
    },
    categoryPage: {
      back: 'جميع المنتجات الذكية',
      available: 'متوفر حالياً',
      future: 'قريباً ضمن المنظومة',
      confirmed: 'منتج مؤكد',
      direction: 'توجه مستقبلي للفئة',
      examples: 'النطاق المخطط للفئة',
      viewProduct: 'عرض المنتج',
    },
    detail: {
      overview: 'نظرة عامة',
      specifications: 'المواصفات الرئيسية',
      environments: 'البيئات المناسبة',
      benefits: 'فوائد الاتصال',
      inquiry: 'طلب استفسار عن المنتج',
      installation: 'مناقشة التركيب',
      related: 'الحل المرتبط',
      back: 'جميع المنتجات',
    },
    notFound: {
      title: 'هذه الصفحة غير متصلة.',
      body: 'ربما تغيّر العنوان أو أن الصفحة غير متاحة.',
      action: 'العودة للرئيسية',
    },
  },
} as const
